// style
#![allow(clippy::redundant_static_lifetimes, clippy::needless_pub_self)]

#[macro_use]
mod _marco;
mod once;
mod version;

pub mod variables {
  use crate::version::Version;
  use std::path::Path;

  #[cold]
  fn initialize() {
    crate::once::initialize(|| unsafe {
      out_dir::initialize();
      cfg_feature::initialize();
      manifest_dir::initialize();
      build_timestamp::initialize();

      // after cfg_feature
      is_preview::initialize();

      // after manifest_dir is_preview
      version_number::initialize();
      // after version_number
      pkg_version::initialize();
    })
  }
  generate_variable_get!(out_dir &'static Path |x| x.as_path());
  generate_variable_get!(build_timestamp u64 |x| *x);
  generate_variable_get!(version_number u16 |x| *x);
  generate_variable_get!(manifest_dir &'static Path |x| x.as_path());
  generate_variable_get!(pkg_version Version |x| *x);
  generate_variable_get!(cfg_feature &'static str |x| x.as_str());
  generate_variable_get!(is_preview bool |x| *x);
}

mod infos {
  use crate::variables::*;
  use std::io::{self, Write};

  fn write_generated<W: Write>(writer: &mut W) -> io::Result<()> {
    writer
      .write_all(b"// This file is automatically @generated by build.rs. Do not edit manually.\n")
  }
  re_export_info_types!(
    build BuildInfo,
    platform PlatformType CURRENT PlatformInfo,
  );
}
pub use infos::prelude::*;
